CREATE TABLE ADMIN_STAFF (
  ID            BIGINT PRIMARY KEY,
  USERNAME      VARCHAR(32)  NOT NULL
  COMMENT '用户名',
  PASSWORD_HASH VARCHAR(128) NOT NULL
  COMMENT '密码(加密过的)',
  ORGANIZATION  BIGINT       NOT NULL
  COMMENT '所属机构, 关联API_ORGANIZATIONS',
  NICKNAME      VARCHAR(64)  NOT NULL
  COMMENT '真实姓名',
  PHONE         VARCHAR(32)  NOT NULL
  COMMENT '电话',
  EMAIL         VARCHAR(32)  NOT NULL
  COMMENT '邮箱',
  STATUS        INT          NOT NULL DEFAULT 1
  COMMENT '状态: 0: 未激活; 1: 激活',
  CREATE_TIME   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COMMENT '后台工作人员';

CREATE INDEX IX_ADMIN_STAFF_ORGANIZATION ON ADMIN_STAFF (ORGANIZATION);
CREATE UNIQUE INDEX UQ_ADMIN_STAFF_USERNAME ON ADMIN_STAFF (USERNAME);
CREATE UNIQUE INDEX UQ_ADMIN_STAFF_PHONE ON ADMIN_STAFF (PHONE);
CREATE UNIQUE INDEX UQ_ADMIN_STAFF_EMAIL ON ADMIN_STAFF (EMAIL);

CREATE TABLE ADMIN_ROLES (
  UID       BIGINT      NOT NULL
  COMMENT '用户ID, 关联ADMIN_STAFF',
  AUTHORITY VARCHAR(32) NOT NULL
  COMMENT '用户权限'
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COMMENT '管理角色';

CREATE INDEX IX_ADMIN_ROLES_UID ON ADMIN_ROLES (UID);
